### ISSUE TITLE
Timelapse() creates mp4 not jpg Timelapse

### ISSUE THREAD

**Issue by Links2004** [Cadair/octoprint-matrix-notifier-plugin#12]
the the Snapshot feature is failing the upload as image on matrix, since the `Timelapse()` class creates a mp4 not jpgs .
which will fail to upload as image (since its a video).

```
/home/pi/.octoprint/timelapse # ls -la
total 4236
-rw-r--r--  1 pi pi 233982 Dez 24 16:19 20211224142144.mp4
-rw-r--r--  1 pi pi 211292 Dez 24 16:19 20211224144202.mp4
.....
```

```
2021-12-24 18:28:10,504 - octoprint.plugin - ERROR - Error while calling plugin matrix_notifier
Traceback (most recent call last):
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_matrix_notifier/plugin.py", line 213, in on_event
    self.send_snapshot()
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_matrix_notifier/plugin.py", line 294, in send_snapshot
    mxc_url = self.client.upload_media(data, "image/jpg")["content_uri"]
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_matrix_notifier/matrix.py", line 77, in upload_media
    content_length=len(media_data),
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_matrix_notifier/matrix.py", line 44, in _send
    resp = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

may a simple option to download the webcam snapshot url disk will do the trick.
or look here:
https://github.com/fraschetti/Octoslack/blob/master/octoprint_Octoslack/__init__.py#L5028

```py
import urllib.request
import shutil

with urllib.request.urlopen(url) as response, open(file_name, 'wb') as out_file:
    shutil.copyfileobj(response, out_file)
```

https://github.com/Cadair/octoprint-matrix-notifier-plugin/blob/4cd53dc705fa2e76ac6a131b9334bd66927f648a/octoprint_matrix_notifier/plugin.py#L241-L254

**Comment by Cadair** [comment]
Should be fixed by #13 and released in 0.3.0
